### ISSUE TITLE
Zlib cannot compress 

### ISSUE THREAD

**Issue by saikat2990** [fichtner/flows_to_weka#2]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/pythonProject/wfe.py", line 98, in <module>
    print ("%s,%s,%s,%s,%s,%s,%.3f,%s,%s,%s,%s,%s,%s"%(proto_name(flow.sport,flow.dport),flow.src,flow.sport,flow.dst,flow.dport,flow.proto,flow.push_flag_ratio(),flow.avrg_len(),flow.avrg_payload_len(),flow.pkt_count,flow.avrg_inter_arrival_time(),flow.kolmogorov(),flow.shannon()))
  File "F:\pythonProject\tcp_stream.py", line 38, in kolmogorov
    return round(kolmogorov(self.payload), 4)
  File "F:\pythonProject\entropy.py", line 36, in kolmogorov
    compr = zlib.compress(data)
TypeError: a bytes-like object is required, not 'str'

**Comment by fichtner** [comment]
Sorry, I should have archived this repository.
